In [2]:
import numpy as np

In [3]:
# implementing Newton's iteration to minimize f(x)
eps_const = 10e-6

In [4]:
# Equation: 2x1**2 + x2**2 - 2x1*x2 + 2x1**3 + x1**4
def calc_df(x1: float, x2: float) -> np.ndarray:
    df = np.array([[(4*x1)-(2*x2)+(6*pow(x1,2))+(4*pow(x1,3))],[(2*x2)-(2*x1)]])
    return df

In [48]:
def calc_hessian(x1: float, x2: float) -> np.ndarray:
    hess = np.array([[(12*pow(x1,2)+(12*x1)+4),-2],[-2,2]])
    return hess

def calc_prereq(x0: np.ndarray) -> tuple:
    del_f = calc_df(x0[0][0], x0[1][0])
    H_f = calc_hessian(x0[0][0], x0[1][0])
    return del_f, H_f

In [50]:

def newton(x0: np.ndarray, del_f: np.ndarray, H_f: np.ndarray, eps: float = 1e-6, max_iter: int=100):
    x = [x0]
    for k in range(max_iter):
        norm_2 = np.linalg.norm(x=del_f, ord=2)
        if norm_2 < eps:
            return x, k, x[-1]
        d = np.linalg.solve(H_f, del_f)
        x.append(x[k] - d)
        del_f = calc_df(x[k+1][0][0], x[k+1][1][0])
        H_f = calc_hessian(x[k+1][0][0], x[k+1][1][0])
    print(f'k:{k}')
    return x, k, x[-1]

def newton_pipeline(x0: np.ndarray, eps: float = 1e-6, max_iter: int=100):
    del_f, H_f = calc_prereq(x0)
    return newton(x0, del_f, H_f)

In [51]:
x0=[np.array([[1],[1]]), np.array([[1],[-1]]), np.array([[2],[-2]])]

In [52]:
ans = []
for xi in x0:
    ans.append([newton_pipeline(x0=xi)])

In [53]:
len(ans)

3

In [54]:
ans[0]

[([array([[1],
          [1]]),
   array([[0.53846154],
          [0.53846154]]),
   array([[0.25028589],
          [0.25028589]]),
   array([[0.08710246],
          [0.08710246]]),
   array([[0.01620003],
          [0.01620003]]),
   array([[0.00073202],
          [0.00073202]]),
   array([[1.60210289e-06],
          [1.60210289e-06]]),
   array([[7.70014343e-12],
          [7.70014343e-12]])],
  7,
  array([[7.70014343e-12],
         [7.70014343e-12]]))]

In [55]:
ans[2]

[([array([[ 2],
          [-2]]),
   array([[1.18918919],
          [1.18918919]]),
   array([[0.66000444],
          [0.66000444]]),
   array([[0.32439061],
          [0.32439061]]),
   array([[0.12640158],
          [0.12640158]]),
   array([[0.03020608],
          [0.03020608]]),
   array([[0.00239946],
          [0.00239946]]),
   array([[1.70809427e-05],
          [1.70809427e-05]]),
   array([[8.7520605e-10],
          [8.7520605e-10]])],
  8,
  array([[8.7520605e-10],
         [8.7520605e-10]]))]